os: linux
arch: ppc64le

services:
  - docker

before_install:
  - docker pull registry.access.redhat.com/ubi7/ubi:latest
  
script:
  - docker run -v `pwd`:/root/build --workdir=/root/build --name ubi7_cockroachdb registry.access.redhat.com/ubi7/ubi:latest /bin/bash -c "bash cockroachdb_ubi7.sh"
